### ISSUE TITLE
Adding content to Kowainik's style guide post

### ISSUE THREAD

**Issue by Rizary** [kowainik/kowainik.github.io#103]
Hi!

I don't know what is the best way to adding content to the [Kowainik Guide](https://kowainik.github.io/posts/2019-02-06-style-guide). So I start this issue with several ideas that come when I tried to follow this guide:

### Prefer guards over if-then-else where possible.

I think we can add the guide about how to write guide (do's and dont's) into the post. What I learn lately regarding guard is to write something like this:
```
combineTwo :: Int -> Int -> (Int, (Int, String))
combineTwo prev curr 
    | True <- prev < 0
    , True <- (prev + curr) == 0
    = (0,((curr),"("++(show 0)++","++(show (curr))++")"))
    | otherwise = ((prev + curr),(0, "("++(show (prev + curr)) ++ "," ++ (show 0) ++")"))   
```
where we put comma (,) if we have multiple cases.

### The field name for a newtype must be prefixed by **un** followed by the type name.
This is very helpful, but if you notice `Kleisli` type that has function type on its field name, it is better to have **run** instead of **un** for example:
```
newtype Execute a c = Execute 
  { unExecute :: a -> IO c }
```
would be better if we have the **run** like `runExecute`.

### The maximum allowed line length is 90 characters. If your line of code exceeds this limit, try to split code into smaller chunks or break long lines over multiple shorter ones.

Between 80-90 of the maximum allowed length characters is really helpful. But, I got confused when I write the following function:

```
executionUnderDeps :: Logger
                   -> (DepCore.HealthCheck healthCheck)
                   -> dependencies
                   -> IO (DepCore.ExecutionUnderDependenciesAcquired dependencies (Either (NonEmpty UnhealthyDependency) ()))
```

Does the above code name should be simplified?

## Additional style
following [tibbe's guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md)
1. Hanging lambda
```
bar :: IO ()
bar = forM_ [1, 2, 3] $ \n -> do
          putStrLn "Here comes a number!"
          print n

foo :: IO ()
foo = alloca 10 $ \a ->
      alloca 20 $ \b ->
      cFunction a b
```
2. Have function arguments be lazy unless you explicitly need them to be strict. The most common case when you need strict function arguments is in recursion with an accumulator.

These are some improvement that I have in my mind right now. I am open for discussion though.

_ps_: if you feel appropriate to change the content, then I'll start the PR on that.

**Comment by chshersh** [comment]
@Rizary Thanks for opening the discussion about possible improvements about our style guide. Here my thoughts about suggestions:

1. I wouldn't write this particular example using Pattern Guards. Using `&&` seems more logical to me. As to general formatting of pattern guards -- our style guide specifies that developers should prefer comma-leading style, so there's no need to write one more example.
2. Prefix `un` for `newtype`s is our naming convention. So if you see a function started with `un`, you have hinted that this most likely a `newtype` unwrapper. Naming conventions in `base` are inconsistent already: some newtypes has `run` prefix, and some have `get` prefix. I think that introducing special vague rules about prefixes when to use `run` vs `un` will complicate the style guide. It's quite easy to add your function with a different name if you find the alternative name more appropriate.
3. You haven't formatted the type signature according to the style guide. If it still doesn't fit, try to use alternative ways to shorten lines. To me, if a type is too long that it doesn't fit into 90 chars limit, it should be simplified.
4. We don't have special rules that force people to write lambdas in hanging style. And I don't think we need to introduce them.
5. Regarding strict function arguments by default: this is already the default Haskell behaviour. So there's no need in the style guide to suggest following the default style.

So, as a conclusion, I think there's no need for the style guide to change in the context of these suggestions.

**Comment by Rizary** [comment]
@chshersh 

Thank you for your comment, and it makes sense. I'll close this issue when I don't have anything to discuss again.

**Comment by Rizary** [comment]
@chshersh Hi! I am going to close this issue after several thoughts:
1. A user style guide will vary over time, and it is very subjective to the creator of the guide. So, instead of changing the guide based on my use case, I think it is better for me to use my current guide on top of this guide.
2. I am not able to think of any further guide that I can add to Kowainik's guide until this moment.
