### ISSUE TITLE
Please add support for RSS

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/kowainik.github.io#109]
Hi.

I hope to subscribe with RSS, one day.

`Planet Haskell`, as always, a great hub to share articles into.

Have a nice.

**Comment by chshersh** [comment]
@Anton-Latukha Thanks for opening the issue! However, the website already implements both RSS and Atom feeds which can be found under the following links:

* https://kowainik.github.io/rss.xml
* https://kowainik.github.io/atom.xml

The link to RSS is also at the bottom of the website.

![Capture](https://user-images.githubusercontent.com/4276606/73275485-168be200-41df-11ea-8b70-b7821a0f2eea.PNG)

So this should already work.

**Comment by chshersh** [comment]
I verified today that I can see the newest blog post from mobile RSS reader (as it always worked before), so I'm closing the issue.

**Comment by Anton-Latukha** [comment]
Sending my dear facepalm to myself.

I've glanced on that panel and moved past it, been looking in and out and around in https://kowainik.github.io/posts.

**Comment by Anton-Latukha** [comment]
You can observe here: https://airtable.com/shrp0GHpXNPXt7DnX

**Comment by Anton-Latukha** [comment]
I don't know you notification setting: @chshersh :arrow_up_small: 

Think that RSS is a solid source of delivering the article into the stream for redactors, of course, if you otherwise ping one of them directly.

**Comment by chshersh** [comment]
@Anton-Latukha Not sure what further actions you're proposing. Kowainik already has RSS feed, and it works. Regarding table on Airtable: we don't maintain this table, so we can't add our RSS there. Regarding Planet Haskell — we were considering adding our feed in there, and probably we'll do this :+1:
