### ISSUE TITLE
Arrow zoo: note on the Pattern Guards 

### ISSUE THREAD

**Issue by Anton-Latukha** [kowainik/kowainik.github.io#170]
About Pattern Guards: https://github.com/kowainik/kowainik.github.io/blob/develop/posts/2021-03-01-arrows-zoo.md#pattern-guard

Pattern Guards have unique (I think) property that they can dispatch on types:
https://github.com/haskell-nix/hnix/blob/9f873ca115a32d462b6c0cfec771ecbf1d292c6c/src/Nix/Render/Frame.hs#L89-L97
Which can not be replaced with the case switch, as far as I know and experienced - only Pattern Guards can do this dispatch on types.

**Comment by chshersh** [comment]
Hi @Anton-Latukha, this feature is not unique to pattern guards. You can actually write the same code using `case-of`. And our blog post already mentions the relation between `case-of` and PatternGuards:

> You can often use it instead of the awkward case-of statements.
