### ISSUE TITLE
https://kowainik.github.io/projects/relude#extra-bonuses broken link

### ISSUE THREAD

**Issue by alexkassil** [kowainik/kowainik.github.io#184]
https://kowainik.github.io/projects/relude#extra-bonuses there is a broken link which goes to https://kowainik.github.io/projects/src/Relude/Extra/Map.hs instead of https://github.com/kowainik/relude/blob/main/src/Relude/Extra/Map.hs when clicking from the README.

My suggestion is when transforming the README into a the website version, to prepend all relative links (like the one https://raw.githubusercontent.com/kowainik/relude/main/README.md here for "`StaticMap` and `DynamicMap` type classes](src/Relude/Extra/Map.hs) as a" to links directly to repo. Another possible way to fix this is to simply change the relative links to absolute links in relude's README, but that isn't as clean

I am happy to make this fix, if I could get a code pointer/explanation of how the website builds from these README :D

**Comment by chshersh** [comment]
@alexkassil Thanks for opening an issue! I believe, a much simpler solution would be to just make the link in the `relude` README absolute 🙂

**Comment by alexkassil** [comment]
Great made pr here: https://github.com/kowainik/relude/pull/392

**Comment by chshersh** [comment]
Hey @alexkassil, thanks for the fix! I've merged the PR in `relude`.

The link on our website will be fixed once we deploy a new version. So I'm closing this issue 🙂
