### ISSUE TITLE
Try to configure automatic site reloading

### ISSUE THREAD

**Issue by ChShersh** [kowainik/kowainik.github.io#61]
See example here:

* https://github.com/rhyskeepence/trigger/blob/master/example/example.yaml

**Comment by sphaso** [comment]
Not sure if you had already considered it, I found this issue:    
https://github.com/jaspervdj/hakyll/issues/140

which leads to:
https://cjwebb.com/posts/hakyll-livereload/

TLDR: it looks like adding a simple JS might be enough and even the suggested solution :)

**Comment by sphaso** [comment]
@ChShersh oh I see, I was under the impression that Hakyll already does that via `stack exec site watch`?

**Comment by ChShersh** [comment]
@sphaso You're righ, `hakyll` does something. But it's not enough in our case :disappointed: 

1. Part of our content is configured in `.hs` files for simplicity reasons. This content is not supposed to be changed often. But it would be really nice to automatically recompile code and rerun `hakyll` each time `.hs` file is changed. 
2. We do some additional file reprocessing. For example, we parse posts in `post-raw/` directory and do some things with them and then we copy those files to `posts/` file. It would be nice to do such things on-the-fly.

**Comment by ChShersh** [comment]
Currently this is not really needed since @vrom911 found really nice way to generate TOC and solving other difficulties with `pandoc` and we have better live site reloading :+1:
