### ISSUE TITLE
Add RSS/Atom feed

### ISSUE THREAD

**Issue by chshersh** [kowainik/kowainik.github.io#68]
It should be possible in theory to implement RSS feed with `hakyll`:

* https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html

Though this issue also requires to solve some design questions:

1. Put RSS icon somewhere on the website.
2. Configure the way to not publish newly added blog post. Sometimes I want to add blog post to the online version just to see how it looks on different devices or share with colleagues that can't build the website at the moment in order to get feedback, but I don't want to publish it to everyone yet.

**Comment by ghuntley** [comment]
Lovely. Thanks.

**Comment by chshersh** [comment]
@ghuntley No worries! The changes have been deployed. You can find the feed here:

* https://kowainik.github.io/rss.xml
