### ISSUE TITLE
Typo on home page

### ISSUE THREAD

**Issue by etiennebatise** [kowainik/kowainik.github.io#71]
Hi all,

I noticed a typo on the main page [here](https://github.com/kowainik/kowainik.github.io/blob/develop/templates/main.html#L103).

Actual 
> "_enahce_"

Should be 
> "_enhance_"

Do you want me to fix it ?

**Comment by ChShersh** [comment]
@etiennebatise Thanks for reporting the typo! It's quite easy to have one... Don't worry, I will fix this now and redeploy the website :slightly_smiling_face:

**Comment by ChShersh** [comment]
@etiennebatise Should be fixed now!
