### ISSUE TITLE
[RFC] Multiple blog post authors?

### ISSUE THREAD

**Issue by chshersh** [kowainik/kowainik.github.io#98]
Sometimes blog posts are written by multiple people. For now we just specify `Kowainik` as an author in such cases. Should we support multiple comma-separated authors?

**Comment by vrom911** [comment]
At the moment it is free text format, so you can write "A and B", but I see what you mean here, it is indeed handy.

**Comment by chshersh** [comment]
@vrom911 Closing this issue, as it is already implemented, and the current solution is fine for me :slightly_smiling_face: Maybe can think more on this while working on #27
